vich_uploader:
    db_driver: orm
    mappings:
        user_image:
            upload_destination: '%upload_directory%'
            namer: vich_uploader.namer_origname
            directory_namer: user.directory.namer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

